### ISSUE TITLE
The shape is not the same in the training

### ISSUE THREAD

**Issue by LeifSun** [Lotayou/densebody_pytorch#34]
After I trained it several epoch ,The problem shows that ：
Traceback (most recent call last):
  File "nohup_train.py", line 120, in <module>
    visualizer.save_results(model.get_current_visuals(), epoch, i)
  File "/data/home/chenyu/data_utils/visualizer.py", line 48, in save_results
    resampled_verts = self.UV_sampler.resample(self.tensor2numpy(fake_UV))
  File "/data/home/chenyu/data_utils/uv_map_generator.py", line 409, in resample
    vt_3d = np.stack(vt_3d)
  File "/opt/conda/lib/python3.6/site-packages/numpy/core/shape_base.py", line 416, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape
can you help me analyze the problem?

**Comment by zhou07** [comment]
Hi,
I have the same problem in the train, and now, do you solve the problem?
